apiVersion: v1
kind: Service
metadata:
  name: ipv4check
  namespace: ipv4check
spec:
  ports:
    - name: tcp
      port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
  selector:
    app: ipv4check
